### ISSUE TITLE
Project not on track

### ISSUE THREAD

**Issue by moriarty** [HBRS-MAAS/project-autobake#1]
A lot of commits but no progress?

<img width="996" alt="screen shot 2017-11-20 at 22 45 03" src="https://user-images.githubusercontent.com/55676/33043145-a30e7d8e-ce44-11e7-9fa6-29540dab3262.png">

That's a lot of README edits...

But nothing has changed in your source code for two weeks, it's the original sample code from @argenos.

<img width="1005" alt="screen shot 2017-11-20 at 22 45 39" src="https://user-images.githubusercontent.com/55676/33043171-c43e5d9e-ce44-11e7-8bef-a129fe577bf8.png">

**Comment by moriarty** [comment]
<img width="1008" alt="screen shot 2017-11-20 at 22 47 44" src="https://user-images.githubusercontent.com/55676/33043195-dc7f43aa-ce44-11e7-987a-d4e55f3f9ec7.png">

All those commits for such an empty README.

**Comment by debaraj-barua** [comment]
Hi,
Most of the work is in another branch (development), we have not yet merged it. We are planning on merging it to the master tomorrow.

**Comment by moriarty** [comment]
For future:

Please commit to small branches per feature and merge more frequently.
