### ISSUE TITLE
Project GUI / Graphical Representation

### ISSUE THREAD

**Issue by moriarty** [HBRS-MAAS/project-autobake#10]
To show a multi agent system with agents spamming the terminal with output isn't very useful to show the process.

The User Interface, doesn't need to be incredibly interactive and feature full at this stage.
We just want to see something running next week.
You should be prepared to iteratively improve and extend it as your systems grow.

The focus, should be to show system overview and the states of the agents, and their scheduled tasks.

**Comment by moriarty** [comment]
HBRS-MAAS/project-awesomebakery#31
HBRS-MAAS/project-autobake#10
HBRS-MAAS/project-zarvis#6
HBRS-MAAS/project-pieceofcake#13
HBRS-MAAS/project-just_a_bakery#10
HBRS-MAAS/project-gabych#5

**Comment by argenos** [comment]
@debaraj-barua before you close this, please add a screenshot of your GUI, since you didn’t attend the lab class
