### ISSUE TITLE
Git branching model

### ISSUE THREAD

**Issue by argenos** [HBRS-MAAS/project-autobake#4]
Please use a [git branching model](http://nvie.com/posts/a-successful-git-branching-model/)

**Comment by debaraj-barua** [comment]
Currently following the model mentioned above.
Branching out on the basis of feature/issue from the _develop_ branch. Once all the current issues are solved in develop, we will merge to master

**Comment by argenos** [comment]
@debaraj-barua @kerikon @ssramitsharma from your branch names, it's hard to see what is a feature, what is a bug and what is documentation. Please try using prefixes.

**Comment by argenos** [comment]
pushing to develop is not following the branching model, e.g. https://github.com/HBRS-MAAS/project-autobake/commit/238b8a69ac11df8ecf21fa6a80f10a1e0e0bcde3

**Comment by debaraj-barua** [comment]
I guess we can close this now.  

Currently all our branches are following the convention, and we have pushed to master. We did undo the commit 238b8a6, however, I think we missed missed to undo this in another branch, and it came back when we merged it to _develop_, and now it's more trouble to revert that considering that it is just one file. 

I guess we can take better care in the future.

**Comment by argenos** [comment]
I think so too! It's alright if you keep that change there, and just keep using the branching model moving forward.

**Comment by argenos** [comment]
@ssramitsharma your commits must group changes in a logical way. You are adding a commit per line added, which is not really contributing to your project. Examples: 4eff5852d5fd3ce42c1b3aeb9f0b54639d6cd5d4, ae9266b1dff4ca6b147878fa51e700ebaa29f542, 855e49be279187feaaf1bcba77e7a559d27a22f1
