### ISSUE TITLE
Setup SonarCloud

### ISSUE THREAD

**Issue by moriarty** [HBRS-MAAS/project-autobake#6]
Please setup SonarCloud integration.

The @HBRS-MAAS/pieceofcake has partially set this up already.
And we're asking all teams to do so, and to go further and also setup the GitHub Plugin

1. HBRS-MAAS/project-pieceofcake#6 <- Why use Sonar? Read here.
2. HBRS-MAAS/project-pieceofcake#7 <- What is the GitHub Plugin? Read here.
3. HBRS-MAAS/project-gabych#4 <- Why use the GitHub Plugin? Read here.

This issue I'm copying to all teams.

**Comment by kerikon** [comment]
SonarCloud is set up and merged into master
