### ISSUE TITLE
Add the email(s) you commit with to GitHub

### ISSUE THREAD

**Issue by moriarty** [HBRS-MAAS/project-autobake#7]
HBRS-MAAS/project-just_a_bakery#8 <- See this issue

HBRS-MAAS/project-just_a_bakery#6 <- See comment in this issue if you want links to keep email address private.

**Comment by moriarty** [comment]
https://github.com/HBRS-MAAS/project-autobake/commit/056703066b3d01b2c96dbea81b453236819a1c2b @kerikon

**Comment by kerikon** [comment]
Added the email in account settings.

**Comment by argenos** [comment]
@ssramitsharma you need to add your email to GitHub, otherwise your commits won't be attributed to you
![screenshot-2017-12-7 hbrs-maas project-autobake](https://user-images.githubusercontent.com/5426039/33716851-0156492e-db58-11e7-9c06-ed743e286d43.png)
